FROM node:23.10.0-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy the source code
COPY frontend/ ./

# Build the app
RUN npm run build

# NOTE: No need to create a frontend container as build output gets copied to the backend container