services:
  frontend-build:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./backend/static:/app/dist

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - frontend-build
    # NOTE: Comment out volumes for this build when deploying!
    volumes:
      - ./backend:/app/backend
      - ./backend/static:/app/backend/static
      - ./backend/database:/app/backend/database

  # Development
  frontend-dev:
    image: node:23.10.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true

  backend-dev:
    image: golang:1.23.2-alpine
    working_dir: /app
    command: sh -c "go run backend/main.go"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
    tty: true
    stdin_open: true

  docs-dev:
    image: node:23.10.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --poll 1000"
    ports:
      - "3000:3000"
    volumes:
      - ./docs:/app
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
