services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    ports:
      - "8080:8080"
    volumes:
      # Use local build
      - ./backend/static:/app/static

  # Development
  frontend-dev:
    image: node:23.10.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true

  backend-dev:
    image: golang:1.23.2-alpine
    working_dir: /app
    command: sh -c "apk add --no-cache gcc musl-dev sqlite-dev && go run main.go"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development
      - CGO_ENABLED=1
    tty: true
    stdin_open: true

  docs-dev:
    image: node:23.10.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --poll 1000"
    ports:
      - "3000:3000"
    volumes:
      - ./docs:/app
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
