name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go:
    name: Go Workflow
    uses: ./.github/workflows/go.yaml
  
  svelte:
    name: Svelte Workflow
    uses: ./.github/workflows/svelte.yaml
    
  docker:
    name: Docker Workflow
    uses: ./.github/workflows/docker.yaml