name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: backend
  
  svelte-lint:
    name: Lint Svelte Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Lint with ESLint
        run: cd frontend && npm run lint

  dockerfile-lint:
    name: Lint Project Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.build
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Show Lint Results
        run: cat hadolint-results.sarif
      
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: dockerfile-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.build
          push: false
          tags: myapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-docker-compose:
    name: Test docker-compose
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build
      run: |
        docker compose -f docker-compose.yaml build
    - name: dev
      run: |
        docker compose -f docker-compose.yaml frontend-dev backend-dev docs-dev
