name: Docker Workflow

on:
  workflow_call:

jobs:
  check-dockerfile-changes:
    name: Check for Dockerfile Changes
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.check-dockerfile.outputs.dockerfile_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Dockerfile.build changes
        id: check-dockerfile
        run: |
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }} | grep -q "Dockerfile.build"; then
            echo "dockerfile_changed=true" >> $GITHUB_OUTPUT
          else
            echo "dockerfile_changed=false" >> $GITHUB_OUTPUT
          fi

  dockerfile-lint:
    name: Lint Project Dockerfile
    runs-on: ubuntu-latest
    needs: check-dockerfile-changes
    if: needs.check-dockerfile-changes.outputs.dockerfile_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.build
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Show Lint Results
        run: cat hadolint-results.sarif
      
  dockerfile-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: 
      - check-dockerfile-changes
      - dockerfile-lint
    if: needs.check-dockerfile-changes.outputs.dockerfile_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.build
          push: false
          tags: myapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max