name: Documentation Workflow

on:
  workflow_call:

jobs:
  check-documentation-changes:
    name: Check for documentation Changes
    runs-on: ubuntu-latest
    outputs:
      documentation_changed: ${{ steps.check-documentation.outputs.documentation_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for documentation changes
        id: check-documentation
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^docs/"; then
            echo "documentation_changed=true" >> $GITHUB_OUTPUT
          else
            echo "documentation_changed=false" >> $GITHUB_OUTPUT
          fi

  doc-build:
    name: Build Documentation
    runs-on: ubuntu-latest
    needs: check-documentation-changes
    if: needs.check-documentation-changes.outputs.documentation_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'docs/package-lock.json'

      - name: Install dependencies
        run: cd docs && npm ci

      - name: Build Documentation
        run: cd docs && npm build