name: Go Workflow

on:
  workflow_call:

jobs:
  go-lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    if: >
      contains(toJSON(github.event.pull_request.changed_files), '.go') ||
      contains(toJSON(github.event.push.commits.*.modified), '.go') ||
      contains(toJSON(github.event.push.commits.*.added), '.go')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: backend
          args: --timeout 10m