name: Go Workflow

on:
  workflow_call:

jobs:
  check-backend-changes:
    name: Check for backend Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for backend changes
        id: check-backend
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^backend/"; then
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi
  
  go-lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    needs: check-backend-changes
    if: needs.check-backend-changes.outputs.backend_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Run Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: backend
          args: --timeout 10m