name: Svelte Workflow

on:
  workflow_call:

jobs:
  check-svelte-changes:
    name: Check for frontend Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for frontend changes
        id: check-dockerfile
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^frontend/"; then
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          fi

  svelte-lint:
    name: Lint Svelte Code
    runs-on: ubuntu-latest
    needs: check-svelte-changes
    if: needs.check-svelte-changes.outputs.frontend_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Lint with ESLint
        run: cd frontend && npm run lint